# Generated by Django 5.2.5 on 2025-09-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_prospect',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
