# Generated by Django 5.2.5 on 2025-09-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('contacts', '0002_contact_is_prospect_contact_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='linked_contacts',
        ),
        migrations.AddField(
            model_name='company',
            name='linked_contacts',
            field=models.ManyToManyField(blank=True, related_name='companies', to='contacts.contact'),
        ),
    ]
