# Generated by Django 5.2.5 on 2025-09-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_linked_contacts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='main_phone',
            new_name='phone',
        ),
    ]
